new branch
bgMargarita/Calculator pull request #1
Opened 2018-11-28 12:19 UTC by bgMargarita

delete strings
edit variable

2018-11-28 12:23 UTC, woainikk commented on src/main/java/com/Margarita/calculator/Parser.java
>                  System.out.println("gdfg");
зачем это?

2018-11-28 12:25 UTC, bgMargarita commented on src/main/java/com/Margarita/calculator/Parser.java
>                  System.out.println("gdfg");
название переменной поменяла

2018-11-28 12:30 UTC, woainikk commented on src/main/java/com/Margarita/calculator/Parser.java
> +    List<String> Array = new ArrayList<String>();
почему название листа с большой буквы? названия переменных с маленькой буквы пишем. для чего этот лист, можно осмысленное название ему дать?

2018-11-28 12:30 UTC, AntipovAndrey commented on src/main/java/com/Margarita/calculator/Parser.java
> +    List<String> Array = new ArrayList<String>();
https://www.oracle.com/technetwork/java/codeconventions-135099.html

2018-11-28 12:32 UTC, woainikk commented on src/main/java/com/Margarita/calculator/Parser.java
>  public class Parser {
пустую строку после этой вставь

2018-11-28 12:55 UTC, bgMargarita commented on src/main/java/com/Margarita/calculator/Parser.java
> +    List<String> Array = new ArrayList<String>();
окей, дадим

2018-11-28 14:21 UTC, woainikk commented on src/main/java/com/Margarita/calculator/Parser.java
>          try {
try with resources

2018-11-28 14:22 UTC, AntipovAndrey commented on src/main/java/com/Margarita/calculator/Parser.java
> +    public void readFromFile() {
Твой метод ничего не возвращает, а вместо этого сохраняет в себя что он прочитал из файла.
Было бы правильнее не делать поля
```
 String filename = "file.txt";
 List<String> Array = new ArrayList<String>();
```
А чтобы твой метод принимал название файла, и сам создавал List, и его возвращал. 
и работа с твоим классом будет такая
```
Parser p = new Parser();
List<String> l = p.readFromFile("filename.txt");
```

2018-11-28 14:22 UTC, AntipovAndrey commented on src/main/java/com/Margarita/calculator/Parser.java
> +    public void readFromFile() {
И по поводу try - catch - finally
Это правильно, что ты закрываешь файл после использования, но с 7 джавы появилась возможность делать это проще
сейчас ты написала
```
BufferedReader readFromFile = null;
try {
   ...
} catch(IOException e) {
  ...
} finally {
   (закртыие файла)
}
```
А можно было 
```
try (BufferedReader readFromFile = new BufferedReader(new FileReader("file.txt"))) {
 ...
} catch (IOExceprion e) {
 ...
}
```
В итоге джава сама за тебя закроет файл при выходе из try-catch блока, и такой способ предпочтительнее

2018-11-28 15:43 UTC, AntipovAndrey commented on src/main/java/com/Margarita/calculator/Parser.java
> +    public List<String> ReadFromFile(String filename) {
именование опять не соболюдено 
с большой буквы только классы
функции, поля и переменные с маленькой

2018-11-28 15:44 UTC, woainikk commented on src/main/java/com/Margarita/calculator/Parser.java
> +                stack.push(str.get(i));
обединить два ифа со скобками в один

2018-11-28 15:48 UTC, AntipovAndrey commented on src/main/java/com/Margarita/calculator/Parser.java
> +                stack.push(str.get(i));
Строки на == не проверяют
надо str.get(i).equals(")")

2018-11-28 15:57 UTC, bgMargarita commented on src/main/java/com/Margarita/calculator/Parser.java
> +    public List<String> ReadFromFile(String filename) {
ай, извините

2018-11-28 16:02 UTC, AntipovAndrey requested changes

2018-11-28 16:02 UTC, AntipovAndrey commented on src/main/java/com/Margarita/calculator/Parser.java
> +        Stack stack = new Stack();
Если ты знаешь какой тип ты хочешь хранить в стеке, то надо это указывать - 
```
Stack<String>
```
Но и Stack это устаревшая коллеция, Сейчас исаользуется
```
Deque<String> stack = new ArrayDeque<>();
```

2018-11-28 16:02 UTC, AntipovAndrey commented on src/main/java/com/Margarita/calculator/Parser.java
> +        OPERATION_PRIORITY.put("*", 1);
Вся логика преобразования в постфиксную запись не очень окей держать в парсере. Задача парсера просто отдеать тебе строку с выражением (или список строк с выражениями), 
дальше ты эту строку отдаешь уже калькулятору, типа 
```
calculator.fromPostfix(parsedString);
```

2018-11-28 16:02 UTC, AntipovAndrey commented on src/main/java/com/Margarita/calculator/Parser.java
> +            readFromFile = new BufferedReader(new FileReader(filename));
Теперь ты вообще не закрываешь файл никак. 
надо написать 
```
try (BufferedReader readFromFile = new BufferedReader(new FileReader(filename))) {
}
```
А сверху это удаляешь
```
BufferedReader readFromFile = null;
```

2018-11-28 16:33 UTC, woainikk commented on src/main/java/com/Margarita/calculator/Calculator.java
> +public class Calculator {
вставить пустую строку

2018-11-28 16:35 UTC, woainikk commented on src/main/java/com/Margarita/calculator/Parser.java
> +
удалить пустую строку

2018-11-28 16:35 UTC, woainikk commented on src/main/java/com/Margarita/calculator/Parser.java
> +
удалить пустую строку

2018-11-30 15:47 UTC, woainikk commented on src/main/java/com/Margarita/calculator/Calculator.java
> +        else if (operator.equals("*") || operator.equals("/"))
зачем тут else ?

2018-11-30 16:25 UTC, AntipovAndrey requested changes

2018-11-30 16:25 UTC, AntipovAndrey commented on src/main/java/com/Margarita/calculator/Calculator.java
> +    private int calculate(Integer operand1, Integer operand2, String operator) {
Я думаю все же, что ты не только с интами можешь работать

2018-11-30 16:25 UTC, AntipovAndrey commented on src/main/java/com/Margarita/calculator/Calculator.java
> +    private int calculate(Integer operand1, Integer operand2, String operator) {
Я думаю будет правильнее завести интерфейс Operator (или можно назвать Function), 
там можно определить один метод, например evaluate
Она принимает два double
```java
interface Operator {
    double call(double a, double b); 
}
```
Дальше какая схема - ты делаешь несколько имплементаций (классы оч короткими выйдут)
```java
class PlusOperator implements Operator {

    @Override
    public double evaluate(double a, double b) {
        return a + b;
    }
}
```
После создания основных операторов ты делаешь мап в калькуляторе
и делаешь что-то вроде
```java
operatirs.put("+", new PlusOperator());
operatirs.put("-", new MinusOperator());
```
И далее, твой метод будет выглядить очень коротко
```java
double calculate(double operand1, double operand2, String operator) {
    operators.get(operator).evaluate(operand1, operand2)
}
```
Огромный плюс такого подхода в том, что можно будет добавить новые операторы всего-лишь добавив в мапу новую реализацию того интерфейса, и все само заработает

2018-11-30 16:25 UTC, AntipovAndrey commented on src/main/java/com/Margarita/calculator/Calculator.java
> +
обычно про кодстайл не пишу, но не надо оставлять дыры в коде, 
отделять путой сторокой класс и его поля это ок, но в методе не надо такого
в методе окей отделять какие-то логические куски (но обычно такое вообще можно на более мелкие методы разбить)

2018-11-30 16:25 UTC, AntipovAndrey commented on src/main/java/com/Margarita/calculator/Parser.java
> +    private String line;
не думаю, что тебе тут нужно именно поле, если оно используется только в одном методе класса. Можно сделать обычной переменной

2018-12-03 15:03 UTC, merged